### ISSUE TITLE
How to get .kcf file from SMILES

### ISSUE THREAD

**Issue by rflameiro** [HassounLab/GNN-SOM#1]
In the Notebook, it is stated that "any format supported by RDKit could be used as an input"

However, this does not work, because the mol object needs to have a valid atom.GetProp('kcfType'), that is defined in MolFromKcf.py

To convert from SMILES to the workable .kcf format:

```
# Convert SMILES to .mol file using RDKit 

# Create RDKit mol object
molecule = 'CC1([C@@H]2[C@H]1[C@H](N(C2)C(=O)[C@H](C(C)(C)C)NC(=O)C(F)(F)F)C(=O)N[C@@H](C[C@@H]3CCNC3=O)C#N)C'
molecule = Chem.MolFromSmiles(molecule)
molecule = Chem.AddHs(molecule)

# Compute 2D coordenates and write to .mol file
AllChem.Compute2DCoords(molecule)
print(Chem.MolToMolBlock(molecule), file=open("molecule.mol", 'a+'))
```

In a separate cell:

```
# Convert .mol to .kcf (KEGG format used in the paper) 
# https://iwatobipen.wordpress.com/2016/12/23/convert-chemical-file-format/
# https://www.genome.jp/tools/gn_ca_tools_api.html
!curl -F molfile=@molecule.mol http://rest.genome.jp/mol2kcf/ > molecule.kcf
```

Finally, define the mol object using `MolFromKcfFile`:

```
# Define mol
mol = MolFromKcfFile('molecule.kcf')
```

Then, run the rest of the Notebook as provided.

Congrats for a great work and thank you for making it open access.

**Comment by vporokhin** [comment]
Thank you for your feedback! Indeed, KEGG atom types need to be provided with the molecule for the model to work as intended. We updated the notebook to include a fix based on your suggested approach.
